"""Local Postgres lifecycle via Docker Compose.

Zero-config: ``up`` auto-detects a free host port (5432 collisions with a
Homebrew Postgres or a stale project are the #1 local-dev failure) and persists
the chosen port to project config so every later command reaches the right
instance.
"""

from __future__ import annotations

import shutil
import socket
import subprocess
import time

from .config import Project

POSTGRES_IMAGE = "postgres:16"


def _find_free_port(preferred: int = 5432, attempts: int = 64) -> int:
    for port in range(preferred, preferred + attempts):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            try:
                s.bind(("127.0.0.1", port))
                return port
            except OSError:
                continue
    raise RuntimeError(
        f"could not find a free host port in range {preferred}..{preferred + attempts}"
    )


def _docker_bin() -> str:
    exe = shutil.which("docker")
    if not exe:
        raise RuntimeError(
            "`docker` not found on PATH. Install Docker Desktop (or Colima/Podman "
            "with a docker shim) — dbmachine manages a local Postgres container."
        )
    return exe


def compose_yaml(proj: Project) -> str:
    c = proj.config
    return f"""\
# Generated by dbmachine. Manages this project's local Postgres.
services:
  db:
    image: {POSTGRES_IMAGE}
    container_name: {c.container}
    environment:
      POSTGRES_USER: {c.db_user}
      POSTGRES_PASSWORD: {c.db_password}
      POSTGRES_DB: {c.db_name}
    ports:
      - "{c.port}:5432"
    volumes:
      - {c.container}_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {c.db_user} -d {c.db_name}"]
      interval: 2s
      timeout: 3s
      retries: 30
volumes:
  {c.container}_data:
"""


def _compose_path(proj: Project):
    return proj.root / "docker-compose.yaml"


def _compose(proj: Project, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    docker = _docker_bin()
    cmd = [docker, "compose", "-f", str(_compose_path(proj)), *args]
    return subprocess.run(cmd, capture_output=True, text=True, check=check)


def write_compose(proj: Project) -> None:
    _compose_path(proj).write_text(compose_yaml(proj))


def up(proj: Project, *, timeout: float = 90.0) -> dict:
    """Bring up local Postgres on an auto-detected free port."""
    # Pick a fresh free port (keeps current if it's still free).
    chosen = _find_free_port(proj.config.port or 5432)
    proj.config.port = chosen
    proj.save()
    write_compose(proj)

    _compose(proj, "up", "-d")

    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        res = _compose(proj, "ps", "--format", "json", check=False)
        if "healthy" in res.stdout:
            return {
                "status": "up",
                "container": proj.config.container,
                "port": chosen,
                "url": proj.config.url(),
            }
        time.sleep(2)
    raise RuntimeError(
        f"Postgres did not become healthy within {timeout:.0f}s. "
        f"Check `docker compose -f {_compose_path(proj)} logs`."
    )


def down(proj: Project, *, destroy: bool = False) -> dict:
    write_compose(proj)
    args = ["down"]
    if destroy:
        args.append("-v")  # also remove the data volume
    _compose(proj, *args, check=False)
    return {"status": "down", "container": proj.config.container, "destroyed": destroy}


def status(proj: Project) -> dict:
    if not _compose_path(proj).exists():
        return {"running": False, "reason": "no compose file (run `dbmachine up`)"}
    res = _compose(proj, "ps", "--format", "json", check=False)
    running = "running" in res.stdout or "healthy" in res.stdout
    return {
        "running": running,
        "healthy": "healthy" in res.stdout,
        "container": proj.config.container,
        "port": proj.config.port,
        "url": proj.config.url() if running else None,
    }
