"""Agent instructions generator.

``AGENTS.md`` is intentionally a **thin overview + index** — the app's purpose,
the list of entities/operations, and pointers to the granular ``describe`` /
``inspect`` commands. It is NOT a full data-dictionary dump (that would consume
tens of thousands of tokens and blow out the context window as the schema
grows). The full dictionary is written separately to the build dir for when a
human wants the whole picture.
"""

from __future__ import annotations

from .introspect import describe_entity
from .spec import Spec


def generate_agents_md(spec: Spec) -> str:
    app = spec.app
    lines: list[str] = []
    lines.append(f"# {app.name} — agent guide")
    lines.append("")
    if app.description:
        lines.append(app.description.strip())
        lines.append("")
    lines.append(
        "This backend is built and operated with **dbmachine**: a Postgres "
        "database exposed through a self-documenting CLI. Invariants are enforced "
        "in the database, not in this prompt — you cannot corrupt data even if you "
        "issue a wrong command; the DB will reject it."
    )
    lines.append("")

    lines.append("## How to operate this app")
    lines.append("")
    lines.append("All commands accept `--json` and emit machine-readable JSON on stdout.")
    lines.append("")
    lines.append("```")
    lines.append("dbmachine inspect                 # overview of entities & operations")
    lines.append("dbmachine describe <entity>       # full schema for one entity")
    lines.append("dbmachine create <entity> --json '{...}'")
    lines.append("dbmachine list <entity> [--where col=val] [--limit N]")
    lines.append("dbmachine get <entity> <id>")
    lines.append("dbmachine update <entity> <id> --json '{...}'")
    lines.append("dbmachine do <operation> --json '{...}'   # typed custom actions")
    lines.append("dbmachine query --sql 'SELECT ...'        # read-only SQL / views")
    lines.append("dbmachine import <file> --entity <entity> # CSV/JSON/Excel ingest")
    lines.append("dbmachine audit [--entity <entity>]       # change history")
    lines.append("```")
    lines.append("")
    lines.append(
        "**Pull only what you need.** Don't read the whole schema up front — run "
        "`dbmachine describe <entity>` for the task at hand."
    )
    lines.append("")

    lines.append("## Entities")
    lines.append("")
    for name, e in spec.entities.items():
        desc = (e.description or "").strip().replace("\n", " ")
        lines.append(f"- **`{name}`** — {desc} → `dbmachine describe {name}`")
    lines.append("")

    if spec.operations:
        lines.append("## Operations (beyond CRUD)")
        lines.append("")
        for name, o in spec.operations.items():
            desc = (o.description or "").strip().replace("\n", " ")
            req = [i for i, v in o.inputs.items() if v.required]
            lines.append(f"- **`{name}`** — {desc} (inputs: {', '.join(req) or 'none'})")
        lines.append("")

    if spec.views:
        lines.append("## Views (read-only, for analytics/BI)")
        lines.append("")
        for name, v in spec.views.items():
            desc = (v.description or "").strip().replace("\n", " ")
            lines.append(f"- **`{name}`** — {desc} → `dbmachine query --sql 'SELECT * FROM {name}'`")
        lines.append("")

    lines.append("## Guarantees")
    lines.append("")
    lines.append("- Required fields, types, enums and uniqueness are enforced by Postgres.")
    lines.append("- Structural invariants (e.g. exclusion constraints) make illegal states impossible.")
    lines.append("- Every write is recorded in an audit log (`dbmachine audit`).")
    lines.append("- The spec (`app.dbm.yaml`) is the source of truth — change it, then `dbmachine migrate`.")
    lines.append("")
    lines.append("_Generated by dbmachine. Regenerated on every `compile` / `docs`._")
    lines.append("")
    return "\n".join(lines)


def generate_data_dictionary(spec: Spec) -> str:
    """The full, heavy data dictionary (written to the build dir, not loaded by default)."""
    lines = [f"# {spec.app.name} — data dictionary", ""]
    for name in spec.entities:
        d = describe_entity(spec, name)
        lines.append(f"## {name}")
        lines.append("")
        if d["description"]:
            lines.append(d["description"].strip())
            lines.append("")
        lines.append("| field | type | required | unique | description |")
        lines.append("|---|---|---|---|---|")
        for f in d["fields"]:
            t = f["type"] + (f" ({f['enum']})" if f.get("enum") else "")
            lines.append(
                f"| `{f['name']}` | {t} | {'yes' if f['required'] else ''} | "
                f"{'yes' if f.get('unique') else ''} | {(f.get('description') or '').strip()} |"
            )
        lines.append("")
        if d["relationships"]:
            lines.append("**Relationships:**")
            lines.append("")
            for r in d["relationships"]:
                lines.append(f"- `{r['name']}` — {r['kind']} → `{r['target']}`")
            lines.append("")
        for chk in d["checks"]:
            lines.append(f"- *check* `{chk['name']}`: `{chk['expr']}`")
        for exc in d["exclusions"]:
            lines.append(f"- *exclusion* `{exc['name']}`: {(exc.get('description') or '').strip()}")
        lines.append("")
    return "\n".join(lines)
